### ISSUE TITLE
'intl' library incompatibility, install failed

### ISSUE THREAD

**Issue by zthrive** [BirjuVachhani/firestore_size#1]
**Describe the bug**
Failed to install with bellow message. Could you please upgrade the version of your package?
Because every version of firestore_size depends on intl ^0.18.0 and <my project> depends on intl ^0.19.0, firestore_size is forbidden.
So, because <my project> depends on firestore_size any, version solving failed.

**To Reproduce**
flutter pub add firestore_size (if you use later version of intl package)

**Comment by BirjuVachhani** [comment]
@zthrive Thank you for reporting this. I've published a new version that should fix it!

**Comment by zthrive** [comment]
Thanks a lot
